# Generated by Django 3.2 on 2021-04-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcycurricula',
            name='rangeusers',
            field=models.CharField(blank=True, db_column='RangeUsers', default='1', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='rangeusers',
            field=models.CharField(blank=True, db_column='RangeUsers', default='1', max_length=4096, null=True),
        ),
    ]
