# Generated by Django 3.0 on 2021-03-17 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210317_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcyrunningaccount',
            name='id_plan',
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='aboutspeaker',
            field=models.CharField(blank=True, db_column='AboutSpeaker', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='attr',
            field=models.IntegerField(blank=True, db_column='Attr', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='charge',
            field=models.IntegerField(blank=True, db_column='Charge', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='dooropen',
            field=models.IntegerField(blank=True, db_column='DoorOpen', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='id',
            field=models.IntegerField(db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='listdepts',
            field=models.CharField(blank=True, db_column='ListDepts', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='listplaces',
            field=models.CharField(blank=True, db_column='ListPlaces', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='mapuser2equ',
            field=models.CharField(blank=True, db_column='MapUser2Equ', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='name',
            field=models.CharField(blank=True, db_column='Name', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='pwaccess',
            field=models.IntegerField(blank=True, db_column='PwAccess', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='pwcontinuous',
            field=models.IntegerField(blank=True, db_column='PwContinuous', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='pwdirection',
            field=models.IntegerField(blank=True, db_column='PwDirection', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='rangeequs',
            field=models.CharField(blank=True, db_column='RangeEqus', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='rangeusers',
            field=models.CharField(blank=True, db_column='RangeUsers', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='rem',
            field=models.CharField(blank=True, db_column='Rem', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='timebegin',
            field=models.IntegerField(blank=True, db_column='TimeBegin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='timebegincheckbegin',
            field=models.IntegerField(blank=True, db_column='TimeBeginCheckBegin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='timebegincheckend',
            field=models.IntegerField(blank=True, db_column='TimeBeginCheckEnd', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='timeend',
            field=models.IntegerField(blank=True, db_column='TimeEnd', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='timeendcheckbegin',
            field=models.IntegerField(blank=True, db_column='TimeEndCheckBegin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='timeendcheckend',
            field=models.IntegerField(blank=True, db_column='TimeEndCheckEnd', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcydept',
            name='id',
            field=models.IntegerField(db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcydept',
            name='id_parent',
            field=models.IntegerField(db_column='ID_Parent', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcydept',
            name='idmanager',
            field=models.IntegerField(db_column='IdManager', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcydept',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcydept',
            name='name',
            field=models.CharField(db_column='Name', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcydept',
            name='timeupdate',
            field=models.IntegerField(db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='class_field',
            field=models.IntegerField(blank=True, db_column='Class', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='dx',
            field=models.IntegerField(blank=True, db_column='Dx', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='dy',
            field=models.IntegerField(blank=True, db_column='Dy', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='id_ip',
            field=models.CharField(blank=True, db_column='ID_IP', default='1', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='id_location_sn',
            field=models.IntegerField(blank=True, db_column='ID_Locatio_SN', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='itimebegin',
            field=models.IntegerField(blank=True, db_column='iTimeBegin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='itimelogin',
            field=models.IntegerField(blank=True, db_column='iTimeLogin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='key0k',
            field=models.IntegerField(blank=True, db_column='Key0k', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='keycancel',
            field=models.IntegerField(blank=True, db_column='KeyCancel', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='keydel',
            field=models.IntegerField(blank=True, db_column='KeyDel', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='keyf1',
            field=models.IntegerField(blank=True, db_column='KeyF1', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='link',
            field=models.IntegerField(blank=True, db_column='Link', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='listplaces',
            field=models.CharField(blank=True, db_column='ListPlaces', default='1', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='login',
            field=models.IntegerField(blank=True, db_column='Login', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='mac',
            field=models.CharField(blank=True, db_column='MAC', default='1', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='name',
            field=models.CharField(blank=True, db_column='Name', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='onall',
            field=models.IntegerField(blank=True, db_column='OnAll', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='portlisten',
            field=models.IntegerField(blank=True, db_column='PortListen', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='rangeequs',
            field=models.CharField(blank=True, db_column='RangeEqus', default='1', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='rem',
            field=models.CharField(blank=True, db_column='Rem', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='state',
            field=models.IntegerField(blank=True, db_column='State', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='timedelay',
            field=models.IntegerField(blank=True, db_column='TimeDelay', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='type_field',
            field=models.IntegerField(blank=True, db_column='Type', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='whitelist',
            field=models.CharField(blank=True, db_column='WhiteList', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocation',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcylocation',
            name='id_parent',
            field=models.IntegerField(blank=True, db_column='ID_Parent', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocation',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocation',
            name='name',
            field=models.CharField(blank=True, db_column='Name', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocation',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='attr',
            field=models.IntegerField(blank=True, db_column='Attr', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='datebegin',
            field=models.IntegerField(blank=True, db_column='DateBegin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='dateend',
            field=models.IntegerField(blank=True, db_column='DateEnd', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='delaycharged',
            field=models.IntegerField(blank=True, db_column='DelayCharged', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='enabledelaycharged',
            field=models.IntegerField(blank=True, db_column='EnableDelayCharged', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='enablelimittime_xj',
            field=models.IntegerField(blank=True, db_column='EnableLimitTime_XJ', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='enablelimityue_sj',
            field=models.IntegerField(blank=True, db_column='EnableLimitYuE_SJ', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='enablelimityue_xj',
            field=models.IntegerField(blank=True, db_column='EnableLimitYuE_XJ', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='enablemincost',
            field=models.IntegerField(blank=True, db_column='EnableMinCost', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='enablewarntime',
            field=models.IntegerField(blank=True, db_column='EnableWarnTime', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='enablewarnyue',
            field=models.IntegerField(blank=True, db_column='EnableWarnYuE', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='getequip',
            field=models.IntegerField(blank=True, db_column='GetEquIp', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='getequmac',
            field=models.IntegerField(blank=True, db_column='GetEquMac', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='getequname',
            field=models.IntegerField(blank=True, db_column='GetEquName', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='limittime_xj',
            field=models.IntegerField(blank=True, db_column='LimitTime_XJ', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='limityue_sj',
            field=models.IntegerField(blank=True, db_column='LimitYuE_SJ', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='limityue_xj',
            field=models.IntegerField(blank=True, db_column='LimitYuE_XJ', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='mincost',
            field=models.IntegerField(blank=True, db_column='MinCost', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='moderun',
            field=models.IntegerField(blank=True, db_column='ModeRun', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='modeshangji',
            field=models.IntegerField(blank=True, db_column='ModeShangJi', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='price',
            field=models.IntegerField(blank=True, db_column='Price', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='priceminute',
            field=models.IntegerField(blank=True, db_column='PriceMinute', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='warntime',
            field=models.IntegerField(blank=True, db_column='WarnTime', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='warnyue',
            field=models.IntegerField(blank=True, db_column='WarnYuE', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmx',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcymmx',
            name='id_data',
            field=models.IntegerField(blank=True, db_column='ID_Data', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmx',
            name='id_type',
            field=models.IntegerField(blank=True, db_column='ID_Type', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmx',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmx',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmxdata',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmxdata',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='aboutspeaker',
            field=models.CharField(blank=True, db_column='AboutSpeaker', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='attr',
            field=models.IntegerField(blank=True, db_column='Attr', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='charge',
            field=models.IntegerField(blank=True, db_column='Charge', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='dooropen',
            field=models.IntegerField(blank=True, db_column='DoorOpen', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='listdepts',
            field=models.CharField(blank=True, db_column='ListDepts', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='listplaces',
            field=models.CharField(blank=True, db_column='ListPlaces', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='mapuser2equ',
            field=models.CharField(blank=True, db_column='MapUser2Equ', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='pwaccess',
            field=models.IntegerField(blank=True, db_column='PwAccess', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='pwcontinuous',
            field=models.IntegerField(blank=True, db_column='PwContinuous', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='pwdirection',
            field=models.IntegerField(blank=True, db_column='PwDirection', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='rangeequs',
            field=models.CharField(blank=True, db_column='RangeEqus', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='rangeusers',
            field=models.CharField(blank=True, db_column='RangeUsers', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='rem',
            field=models.CharField(blank=True, db_column='Rem', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='timebegin',
            field=models.IntegerField(blank=True, db_column='TimeBegin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='timebegincheckbegin',
            field=models.IntegerField(blank=True, db_column='TimeBeginCheckBegin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='timebegincheckend',
            field=models.IntegerField(blank=True, db_column='imeBeginCheckEnd', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='timeend',
            field=models.IntegerField(blank=True, db_column='TimeEnd', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='timeendcheckbegin',
            field=models.IntegerField(blank=True, db_column='TimeEndCheckBegin', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='timeendcheckend',
            field=models.IntegerField(blank=True, db_column='TimeEndCheckEnd', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='money',
            field=models.IntegerField(blank=True, db_column='Money', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='param1',
            field=models.IntegerField(blank=True, db_column='Param1', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='param2',
            field=models.OneToOneField(db_column='ID_Plan', on_delete=django.db.models.deletion.CASCADE, related_name='runningaccount_related_to_plan', to='polls.TCyplan'),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='time',
            field=models.IntegerField(blank=True, db_column='Time', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='type',
            field=models.IntegerField(blank=True, db_column='Type', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcytableinfo',
            name='id',
            field=models.IntegerField(db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcytableinfo',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcytableinfo',
            name='name',
            field=models.CharField(db_column='Name', default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tcytableinfo',
            name='nametable',
            field=models.CharField(db_column='NameTable', default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tcytableinfo',
            name='timeupdate',
            field=models.IntegerField(db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcytypera',
            name='id_parent',
            field=models.IntegerField(blank=True, db_column='ID_Parent', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcytypera',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcytypera',
            name='name',
            field=models.CharField(blank=True, db_column='Name', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcytypera',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='attr',
            field=models.IntegerField(db_column='Attr', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='attrjf',
            field=models.IntegerField(db_column='AttrJf', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='id',
            field=models.IntegerField(db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='idmanager',
            field=models.IntegerField(blank=True, db_column='IdManager', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='localid',
            field=models.CharField(db_column='LocalID', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='name',
            field=models.CharField(db_column='Name', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='nocard',
            field=models.CharField(db_column='Nocard', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='nouser',
            field=models.CharField(db_column='NoUser', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='psw',
            field=models.CharField(db_column='Psw', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='sex',
            field=models.IntegerField(db_column='Sex', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='timeupdate',
            field=models.IntegerField(db_column='TimeUpdate', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='yue',
            field=models.IntegerField(db_column='Yue', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='yue2',
            field=models.IntegerField(db_column='Yue2', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuserex',
            name='imark',
            field=models.IntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuserex',
            name='rem',
            field=models.CharField(blank=True, db_column='Rem', default='1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuserex',
            name='timeupdate',
            field=models.IntegerField(blank=True, db_column='TimeUpdate', default=1, null=True),
        ),
    ]
