# Generated by Django 3.0 on 2021-03-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210317_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcyequipment',
            name='key0k',
        ),
        migrations.AddField(
            model_name='tcyequipment',
            name='keyOk',
            field=models.IntegerField(blank=True, db_column='KeyOk', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcylocation',
            name='rem',
            field=models.CharField(blank=True, db_column='Rem', default='1', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='id_location_sn',
            field=models.IntegerField(blank=True, db_column='ID_Location_SN', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='param2',
            field=models.OneToOneField(db_column='Param2', on_delete=django.db.models.deletion.CASCADE, related_name='runningaccount_related_to_plan', to='polls.TCyplan'),
        ),
    ]
