# Generated by Django 3.0 on 2021-03-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210318_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='param2',
            field=models.ForeignKey(db_column='Param2', on_delete=django.db.models.deletion.CASCADE, related_name='runningaccount_related_to_plan', to='polls.TCyplan'),
        ),
    ]
