# Generated by Django 3.0 on 2021-04-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210413_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcyuserex',
            name='photo',
            field=models.BinaryField(blank=True, db_column='FaceFearture'),
        ),
    ]
