# Generated by Django 3.0 on 2021-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210413_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcyuserex',
            name='photo_dataf',
        ),
        migrations.AddField(
            model_name='tcyuser',
            name='email',
            field=models.EmailField(db_column='Email', default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tcyuser',
            name='phone',
            field=models.IntegerField(db_column='Phone', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='attr',
            field=models.SmallIntegerField(blank=True, db_column='Attr', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='charge',
            field=models.SmallIntegerField(blank=True, db_column='Charge', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='dooropen',
            field=models.SmallIntegerField(blank=True, db_column='DoorOpen', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='pwaccess',
            field=models.SmallIntegerField(blank=True, db_column='PwAccess', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='pwcontinuous',
            field=models.SmallIntegerField(blank=True, db_column='PwContinuous', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcycurricula',
            name='pwdirection',
            field=models.SmallIntegerField(blank=True, db_column='PwDirection', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcydept',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='class_field',
            field=models.SmallIntegerField(blank=True, db_column='Class', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='id_location_sn',
            field=models.SmallIntegerField(blank=True, db_column='ID_Location_SN', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='keyOk',
            field=models.SmallIntegerField(blank=True, db_column='KeyOk', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='keycancel',
            field=models.SmallIntegerField(blank=True, db_column='KeyCancel', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='keydel',
            field=models.SmallIntegerField(blank=True, db_column='KeyDel', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='keyf1',
            field=models.SmallIntegerField(blank=True, db_column='KeyF1', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='link',
            field=models.SmallIntegerField(blank=True, db_column='Link', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='login',
            field=models.SmallIntegerField(blank=True, db_column='Login', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='onall',
            field=models.SmallIntegerField(blank=True, db_column='OnAll', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyequipment',
            name='state',
            field=models.SmallIntegerField(blank=True, db_column='State', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocation',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='attr',
            field=models.SmallIntegerField(blank=True, db_column='Attr', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocationex',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmx',
            name='id_type',
            field=models.SmallIntegerField(blank=True, db_column='ID_Type', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmx',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcymmxdata',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='attr',
            field=models.SmallIntegerField(blank=True, db_column='Attr', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='charge',
            field=models.SmallIntegerField(blank=True, db_column='Charge', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='dooropen',
            field=models.SmallIntegerField(blank=True, db_column='DoorOpen', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='pwaccess',
            field=models.SmallIntegerField(blank=True, db_column='PwAccess', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='pwcontinuous',
            field=models.SmallIntegerField(blank=True, db_column='PwContinuous', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyplan',
            name='pwdirection',
            field=models.SmallIntegerField(blank=True, db_column='PwDirection', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyrunningaccount',
            name='type_field',
            field=models.SmallIntegerField(blank=True, db_column='Type', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcytableinfo',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcytypera',
            name='imark',
            field=models.SmallIntegerField(db_column='IMark', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='attr',
            field=models.SmallIntegerField(db_column='Attr', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='attrjf',
            field=models.SmallIntegerField(db_column='AttrJf', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuser',
            name='sex',
            field=models.SmallIntegerField(db_column='Sex', default=1, null=True),
        ),
    ]
