# Generated by Django 3.0 on 2021-03-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210317_2327'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tcyrunningaccount',
            table='t_cyrunningaccount',
        ),
    ]
