# Generated by Django 3.0 on 2021-03-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210321_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcyequipment',
            name='id_plan',
            field=models.IntegerField(blank=True, db_column='ID_Plan', default=1, null=True),
        ),
    ]
