# Generated by Django 3.0 on 2021-04-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210322_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcydept',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tcylocationex',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tcymmx',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tcymmxdata',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tcyrunningaccount',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tcytableinfo',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tcytypera',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tcyuser',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tcylocation',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tcyuserex',
            name='rem',
            field=models.CharField(db_column='Rem', default='1', max_length=64, null=True),
        ),
    ]
